#build stage
FROM maven:3-openjdk-11 AS builder
RUN git clone https://github.com/spring-projects/spring-petclinic.git
RUN cd /spring-petclinic/&& mvn package

#deploy stage
FROM openjdk:17
COPY --from=builder /spring-petclinic/target/spring-petclinic*.jar /spring-petclinic.jar
EXPOSE 8080
CMD [ "java","-jar","/spring-petclinic,jar"]